superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include ('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path
from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name = 'detail'),
    path('new/', views.create, name='create'),
    path('detail/', views.detail, name='detail' ),
    path('edit/<int:hero_id>/', views.edit, name='edit'),
    path('delete/<int:hero_id>/', views.delete, name='delete')
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    hero_id = models.AutoField(auto_created=True, primary_key=True)
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero


# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes' : all_heroes
    }
    return render(request,'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero' : single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        single_hero.name = request.POST.get('name')
        single_hero.alter_ego = request.POST.get('alter_ego')
        single_hero.primary = request.POST.get('primary')
        single_hero.secondary = request.POST.get('secondary')
        single_hero.catchphrase = request.POST.get('catchphrase')
        single_hero.save()
        return HttpResponseRedirect('superheroes:index')
    else:
        return render(request, 'superheroes/edit.html')

def delete(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        single_hero.name = request.POST.get('name')
        single_hero.alter_ego = request.POST.get('alter_ego')
        single_hero.primary = request.POST.get('primary')
        single_hero.secondary = request.POST.get('secondary')
        single_hero.catchphrase = request.POST.get('catchphrase')
        single_hero.delete(request,hero_id)
        return HttpResponseRedirect('superheroes:index')
    else:
        return render(request, 'superheroes/delete.html')

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action "{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        <h2>
        Name: <input type = "text" name = "name" id = "name"><br />
        Alter Ego: <input type = "text" name = "alter_ego" id = "alter_ego"><br />
        Primary Ability: <input type = "text" name = "primary" id = "primary"><br />
        Secondary Ability: <input type = "text" name = "secondary" id = "secondary"><br />
        Catchphrase: <input type = "text" name = "catchphrase" id = "catchphrase"><br />
        <input type = "submit" value = "Add">
        </h2>
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Hero</title>
</head>
<body>
    <form action "{% url 'superheroes:delete' %}" method="post">
        {% csrf_token %}
        <h2>
        Name: <input type = "text" name = "name" id = "name"><br />
        Alter Ego: <input type = "text" name = "alter_ego" id = "alter_ego"><br />
        Primary Ability: <input type = "text" name = "primary" id = "primary"><br />
        Secondary Ability: <input type = "text" name = "secondary" id = "secondary"><br />
        Catchphrase: <input type = "text" name = "catchphrase" id = "catchphrase"><br />
        <input type = "submit" value = "Delete">
        </h2>
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hero Details</title>
</head>
<body>
    <ul>
        {% for detail in single_hero %}
        <li> <h2> {{single_hero.name}}</h2></li>
        <li> <h2> {{single_hero.alter_ego}}</h2></li>
        <li> <h2> {{single_hero.primary_ability}}</h2></li>
        <li> <h2> {{single_hero.secondary_ability}}</h2></li>
        <li> <h2> {{single_hero.catch_phrase}}</h2></li>
        {% endfor %}
      
        <a href = "{% url 'superheroes:edit' single_hero.hero_id %}">Edit All Fields</a> 
        <a href = "{% url 'superheroes:delete' single_hero.hero_id %}">Delete All Fields</a></li>
        
        <a href = "{% url 'superheroes:detail' all_heroes.hero_id %}">See All Hero Details </a>
    </ul>
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero</title>
</head>
<body>
    <form action "{% url 'superheroes:edit' %}" method="post">
        {% csrf_token %}
        <h2>
        Name: <input type = "text" name = "name" id = "name"><br />
        Alter Ego: <input type = "text" name = "alter_ego" id = "alter_ego"><br />
        Primary Ability: <input type = "text" name = "primary" id = "primary"><br />
        Secondary Ability: <input type = "text" name = "secondary" id = "secondary"><br />
        Catchphrase: <input type = "text" name = "catchphrase" id = "catchphrase"><br />
        <input type = "submit" value = "Edit">
        </h2>
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in index.all_heroes %}
        <li> <h2> {{hero.name}} <a href = "{% url 'superheroes:detail' hero_id %}"></h2>Click for details</a></li>
        {% endfor %}
    </ul>
    <a href ="{% url 'superheroes:create' %}">Add New Hero</a>
</body>
</html>